spring:
  application:
    name: demo-1

  datasource:
    url: jdbc:postgresql://localhost:5432/Microservice
    username: postgres
    password: Wow3password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090
